// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api_options.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from api_options.proto</summary>
public static partial class ApiOptionsReflection {

  #region Descriptor
  /// <summary>File descriptor for api_options.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ApiOptionsReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFhcGlfb3B0aW9ucy5wcm90bxogZ29vZ2xlL3Byb3RvYnVmL2Rlc2NyaXB0",
          "b3IucHJvdG8iBwoFRW1wdHkqRgoNQVBJU291cmNlVHlwZRIPCgtTT1VSQ0Vf",
          "Qk9USBAAEhEKDVNPVVJDRV9TRVJWRVIQARIRCg1TT1VSQ0VfQ0xJRU5UEAI6",
          "RQoWbmVlZHNfc2V0dXBfY29ubmVjdGlvbhIeLmdvb2dsZS5wcm90b2J1Zi5N",
          "ZXRob2RPcHRpb25zGI4IIAEoCDoEdHJ1ZTpDChRuZWVkc19hdXRoZW50aWNh",
          "dGlvbhIeLmdvb2dsZS5wcm90b2J1Zi5NZXRob2RPcHRpb25zGI8IIAEoCDoE",
          "dHJ1ZTovCgJpZBIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxiM",
          "CCABKA06ATA6TQoGc291cmNlEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VP",
          "cHRpb25zGI0IIAEoDjIOLkFQSVNvdXJjZVR5cGU6C1NPVVJDRV9CT1RIOi8K",
          "BWlmZGVmEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25zGI4IIAEo",
          "CTozCgNsb2cSHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMYjwgg",
          "ASgIOgR0cnVlOjkKCG5vX2RlbGF5Eh8uZ29vZ2xlLnByb3RvYnVmLk1lc3Nh",
          "Z2VPcHRpb25zGJAIIAEoCDoFZmFsc2U6NAoKYmFzZV9jbGFzcxIfLmdvb2ds",
          "ZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxiRCCABKAk6MwoLZmllbGRfaWZk",
          "ZWYSHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zGJIIIAEoCTo5ChBm",
          "aXhlZF9hcnJheV9zaXplEh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9u",
          "cxjXhgMgASgNOjwKDG5vX3plcm9fY29weRIdLmdvb2dsZS5wcm90b2J1Zi5G",
          "aWVsZE9wdGlvbnMY2IYDIAEoCDoFZmFsc2U6RQoVZml4ZWRfYXJyYXlfc2tp",
          "cF96ZXJvEh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxjZhgMgASgI",
          "OgVmYWxzZTpAChdmaXhlZF9hcnJheV9zaXplX2RlZmluZRIdLmdvb2dsZS5w",
          "cm90b2J1Zi5GaWVsZE9wdGlvbnMY2oYDIAEoCTpHCh5maXhlZF9hcnJheV93",
          "aXRoX2xlbmd0aF9kZWZpbmUSHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRp",
          "b25zGNuGAyABKAk6QQoRcG9pbnRlcl90b19idWZmZXISHS5nb29nbGUucHJv",
          "dG9idWYuRmllbGRPcHRpb25zGNyGAyABKAg6BWZhbHNlOjoKEWNvbnRhaW5l",
          "cl9wb2ludGVyEh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxjRhgMg",
          "ASgJOjwKDGZpeGVkX3ZlY3RvchIdLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9w",
          "dGlvbnMY3YYDIAEoCDoFZmFsc2U6RgodY29udGFpbmVyX3BvaW50ZXJfbm9f",
          "dGVtcGxhdGUSHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zGN6GAyAB",
          "KAk="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::APISourceType), }, new pb::Extension[] { ApiOptionsExtensions.NeedsSetupConnection, ApiOptionsExtensions.NeedsAuthentication, ApiOptionsExtensions.Id, ApiOptionsExtensions.Source, ApiOptionsExtensions.Ifdef, ApiOptionsExtensions.Log, ApiOptionsExtensions.NoDelay, ApiOptionsExtensions.BaseClass, ApiOptionsExtensions.FieldIfdef, ApiOptionsExtensions.FixedArraySize, ApiOptionsExtensions.NoZeroCopy, ApiOptionsExtensions.FixedArraySkipZero, ApiOptionsExtensions.FixedArraySizeDefine, ApiOptionsExtensions.FixedArrayWithLengthDefine, ApiOptionsExtensions.PointerToBuffer, ApiOptionsExtensions.ContainerPointer, ApiOptionsExtensions.FixedVector, ApiOptionsExtensions.ContainerPointerNoTemplate }, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Empty), global::Empty.Parser, null, null, null, null, null)
        }));
  }
  #endregion

}
/// <summary>Holder for extension identifiers generated from the top level of api_options.proto</summary>
public static partial class ApiOptionsExtensions {
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MethodOptions, bool> NeedsSetupConnection =
    new pb::Extension<global::Google.Protobuf.Reflection.MethodOptions, bool>(1038, pb::FieldCodec.ForBool(8304, true));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MethodOptions, bool> NeedsAuthentication =
    new pb::Extension<global::Google.Protobuf.Reflection.MethodOptions, bool>(1039, pb::FieldCodec.ForBool(8312, true));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, uint> Id =
    new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, uint>(1036, pb::FieldCodec.ForUInt32(8288, 0));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, global::APISourceType> Source =
    new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, global::APISourceType>(1037, pb::FieldCodec.ForEnum(8296, x => (int) x, x => (global::APISourceType) x, global::APISourceType.SourceBoth));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, string> Ifdef =
    new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, string>(1038, pb::FieldCodec.ForString(8306, ""));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, bool> Log =
    new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, bool>(1039, pb::FieldCodec.ForBool(8312, true));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, bool> NoDelay =
    new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, bool>(1040, pb::FieldCodec.ForBool(8320, false));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, string> BaseClass =
    new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, string>(1041, pb::FieldCodec.ForString(8330, ""));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string> FieldIfdef =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string>(1042, pb::FieldCodec.ForString(8338, ""));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, uint> FixedArraySize =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, uint>(50007, pb::FieldCodec.ForUInt32(400056, 0));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool> NoZeroCopy =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool>(50008, pb::FieldCodec.ForBool(400064, false));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool> FixedArraySkipZero =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool>(50009, pb::FieldCodec.ForBool(400072, false));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string> FixedArraySizeDefine =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string>(50010, pb::FieldCodec.ForString(400082, ""));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string> FixedArrayWithLengthDefine =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string>(50011, pb::FieldCodec.ForString(400090, ""));
  /// <summary>
  /// pointer_to_buffer: Use pointer instead of array for fixed-size byte fields
  /// When set, the field will be declared as a pointer (const uint8_t *data)
  /// instead of an array (uint8_t data[N]). This allows zero-copy on decode
  /// by pointing directly to the protobuf buffer. The buffer must remain valid
  /// until the message is processed (which is guaranteed for stack-allocated messages).
  /// </summary>
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool> PointerToBuffer =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool>(50012, pb::FieldCodec.ForBool(400096, false));
  /// <summary>
  /// container_pointer: Zero-copy optimization for repeated fields.
  ///
  /// When container_pointer is set on a repeated field, the generated message will
  /// store a pointer to an existing container instead of copying the data into the
  /// message's own repeated field. This eliminates heap allocations and improves performance.
  ///
  /// Requirements for safe usage:
  /// 1. The source container must remain valid until the message is encoded
  /// 2. Messages must be encoded immediately (which ESPHome does by default)
  /// 3. The container type must match the field type exactly
  ///
  /// Supported container types:
  /// - "std::vector&lt;T>" for most repeated fields
  /// - "std::set&lt;T>" for unique/sorted data
  /// - Full type specification required for enums (e.g., "std::set&lt;climate::ClimateMode>")
  ///
  /// Example usage in .proto file:
  ///   repeated string supported_modes = 12 [(container_pointer) = "std::set"];
  ///   repeated ColorMode color_modes = 13 [(container_pointer) = "std::set&lt;light::ColorMode>"];
  ///
  /// The corresponding C++ code must provide const reference access to a container
  /// that matches the specified type and remains valid during message encoding.
  /// This is typically done through methods returning const T&amp; or special accessor
  /// methods like get_options() or supported_modes_for_api_().
  /// </summary>
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string> ContainerPointer =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string>(50001, pb::FieldCodec.ForString(400010, ""));
  /// <summary>
  /// fixed_vector: Use FixedVector instead of std::vector for repeated fields
  /// When set, the repeated field will use FixedVector&lt;T> which requires calling
  /// init(size) before adding elements. This eliminates std::vector template overhead
  /// and is ideal when the exact size is known before populating the array.
  /// </summary>
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool> FixedVector =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool>(50013, pb::FieldCodec.ForBool(400104, false));
  /// <summary>
  /// container_pointer_no_template: Use a non-template container type for repeated fields
  /// Similar to container_pointer, but for containers that don't take template parameters.
  /// The container type is used as-is without appending element type.
  /// The container must have:
  /// - begin() and end() methods returning iterators
  /// - empty() method
  /// Example: [(container_pointer_no_template) = "light::ColorModeMask"]
  ///   generates: const light::ColorModeMask *supported_color_modes{};
  /// </summary>
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string> ContainerPointerNoTemplate =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string>(50014, pb::FieldCodec.ForString(400114, ""));
}

#region Enums
public enum APISourceType {
  [pbr::OriginalName("SOURCE_BOTH")] SourceBoth = 0,
  [pbr::OriginalName("SOURCE_SERVER")] SourceServer = 1,
  [pbr::OriginalName("SOURCE_CLIENT")] SourceClient = 2,
}

#endregion

#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Empty : pb::IMessage<Empty>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Empty> _parser = new pb::MessageParser<Empty>(() => new Empty());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Empty> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ApiOptionsReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Empty() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Empty(Empty other) : this() {
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Empty Clone() {
    return new Empty(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Empty);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Empty other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Empty other) {
    if (other == null) {
      return;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
